# Generated by Django 5.2.9 on 2025-12-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='annual_leave',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.IntegerField(default=6),
        ),
    ]
