# Generated by Django 5.2.9 on 2025-12-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_remove_leavebalance_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='annual_leave',
            new_name='total_balance',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='casual_leave',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='sick_leave',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='casual_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='other_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='sick_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('other', 'Other Leave')], max_length=10),
        ),
    ]
