# Generated by Django 5.2.9 on 2025-12-26 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_rename_annual_leave_leavebalance_total_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager who approved/rejected this leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
